language: bash
os: linux
sudo: enabled
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

install:
  - sudo apt update
  - sudo apt install -y snapd
  - sudo snap install lxd --channel 3.0/stable
  - sudo snap install snapcraft --edge --classic
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - export SNAPNAME="$(grep ^name  snap/snapcraft.yaml | awk '{print $2}' )"
  - sudo /snap/bin/lxc init ubuntu:18.04 snapcraft-$SNAPNAME
  - sudo /snap/bin/lxc start  snapcraft-$SNAPNAME
  - sleep 10 # Ugh. sleep for a bit to make sure snapd is started. FIXME with a better detection of /run/snapd.socket or whatever in the container
  - sudo /snap/bin/lxc config set snapcraft-$SNAPNAME environment.SNAPCRAFT_ENABLE_SILENT_REPORT on
  - sudo /snap/bin/lxc exec "snapcraft-$SNAPNAME" -- /bin/bash -c "snap install snapcraft --edge --classic"
  - sudo /snap/bin/lxc exec "snapcraft-$SNAPNAME" -- /bin/bash -c "apt update"
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
script:
  - export PATH=/snap/bin:$PATH
  - export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
  - export SNAPCRAFT_ENABLE_SILENT_REPORT=on
  - export SNAPCRAFT_BUILD_ENVIRONMENT_CHANNEL_SNAPCRAFT=latest/edge
  - sudo snapcraft
  - sudo cp *.snap "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_success:
  - sudo snap install transfer
  - timeout 180 sudo /snap/bin/transfer "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_failure:
  - sudo journalctl -u snapd
