name: krita
version: 4.1.2
summary: Krita is the digital painting studio for artists
description: Krita is a creative application for raster images. Whether you want to create
 from scratch or work with existing images, Krita is for you. You can work with
 photos or scanned images, or start with a blank slate. Krita supports most
 graphics tablets out of the box.

grade: stable
confinement: strict
base: core18

apps:
  krita:
#    command: kf5-launch usr/bin/krita
    command: desktop-launch $SNAP/usr/bin/krita
    environment:
        "PYTHONHOME": "$SNAP/usr"
    plugs:
#      - kde-frameworks-5-plug # content share itself
      - desktop
      - desktop-legacy
      - x11 # runs with xcb QT platform for now
      - unity7 # Notifications
      - home # give home dir access
      - opengl # QT/QML uses opengl
      - network 
      - network-bind
      - removable-media

#plugs:
#  kde-frameworks-5-plug:
#    interface: content
#    content: kde-frameworks-5-all
#    default-provider: kde-frameworks-5
#    target: kf5

parts:
#  kde-frameworks-5-dev:
#    plugin: dump
#    prime: [-*]
#    source: http://build.neon.kde.org/job/kde-frameworks-5-release_amd64.snap/lastSuccessfulBuild/artifact/kde-frameworks-5-dev_amd64.tar.xz
#  kde-frameworks-5-env:
#    plugin: dump
#    prime: [kf5-launch, kf5]
#    source: http://github.com/apachelogger/kf5-snap-env.git
 
  krita:
#    after: [kde-frameworks-5-dev]
    after: [desktop-qt5, libheif]
    plugin: cmake
#    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DQT_NO_DEBUG=1, "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON", -DCMAKE_CXX_FLAGS="-DKDE_NO_DEBUG_OUTPUT -I$SNAPCRAFT_STAGE/include $CPPFLAGS"]
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DQT_NO_DEBUG=1, "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON", -DCMAKE_CXX_FLAGS="-I$SNAPCRAFT_STAGE/include"]
    source: https://github.com/KDE/krita/archive/v4.1.2.zip
    source-subdir: krita-4.1.2/
    build-packages:
        - build-essential
        - cmake
        - libboost-dev
        - libboost-system-dev
        - libeigen3-dev
        - libexiv2-dev
        - libfftw3-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgl1-mesa-dev
        - libglew-dev
        - libglib2.0-dev
        - libglu1-mesa-dev
        - libgsf-1-dev
        - libgsl-dev
        - libjpeg-dev
        - libgif-dev
        - liblcms2-dev
        - libopenexr-dev
        - libpng-dev
        - libpoppler-qt5-dev
        - libtiff5-dev
        - libvc-dev
        - libopencolorio-dev
        - libraw-dev
        - libx11-dev
        - libxml2-dev
        - libxslt1-dev
        - libxi-dev
        - pkg-config
        - pkg-kde-tools
        - python3-sip-dev
        - python3-sip
        - python3-pyqt5
        - pyqt5-dev
        - pyqt5-dev-tools
        - vc-dev
        - zlib1g-dev
        - libkf5kdcraw-dev
        - shared-mime-info
        - libopenimageio-dev
        - extra-cmake-modules
        - libkf5archive-dev
        - libkf5coreaddons-dev
        - libkf5guiaddons-dev
        - libkf5itemmodels-dev
        - libkf5itemviews-dev
        - libkf5widgetsaddons-dev
        - libkf5i18n-dev
        - libkf5windowsystem-dev
        - libkf5completion-dev
        - libkf5iconthemes-dev
        - libkf5kiocore5
        - libqt5svg5-dev
        - libqt5x11extras5-dev
        - libqt5opengl5-dev
        - libxcb-util-dev
    stage-packages:
        - libboost-system1.65.1
        - libexiv2-14
        - libfftw3-double3
        - libgomp1
        - libgsl23
        - libilmbase12
        - libjpeg8
        - liblcms2-2
        - libopencolorio1v5
        - libopenexr22
        - libpng16-16
        - libstdc++6
        - libtiff5
        - libx11-6
        - libxcb1
        - libxi6
        - zlib1g
        - libraw16
        - libkf5crash5
        - libpoppler-qt5-1
        - python3
  libheif:
    after: [libde265, libx265]
    source: https://github.com/strukturag/libheif.git
    source-tag: 'v1.3.2'
    plugin: autotools
  libde265:
    after: [libx265]
    source: https://github.com/strukturag/libde265.git
    source-tag: 'v1.0.3'
    plugin: autotools
  libx265:
    plugin: nil
    source: https://bitbucket.org/multicoreware/x265/downloads/x265_2.7.tar.gz
    build-packages:
      - cmake
      - yasm
      - on amd64: [ libnuma-dev ]
      - on i386:  [ libnuma-dev ]
      - on arm64: [ libnuma-dev ]
    stage-packages:
      - on amd64: [ libnuma1 ]
      - on i386:  [ libnuma1 ]
      - on arm64: [ libnuma1 ]
    override-build: |
      cd source
      cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/usr"
      make
      make install
    prime:
      - usr/lib
